# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/hah50/Downloads/ece-350-tank-shooter/project_1/project_1.runs/synth_1/.Xil/Vivado-4804-P1-04/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a100tcsg324-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    c:/Users/hah50/Downloads/ece-350-tank-shooter/project_1/project_1.gen/sources_1/ip/clk_wiz_0
    C:/Users/hah50/Downloads/ece-350-tank-shooter/mem_files
    {C:/Users/hah50/Downloads/ece-350-tank-shooter/CPU/Test Files/Memory Files}
  } C:/Xilinx/Vivado/2021.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      rt::read_verilog -include {
    c:/Users/hah50/Downloads/ece-350-tank-shooter/project_1/project_1.gen/sources_1/ip/clk_wiz_0
    C:/Users/hah50/Downloads/ece-350-tank-shooter/mem_files
    {C:/Users/hah50/Downloads/ece-350-tank-shooter/CPU/Test Files/Memory Files}
  } {
      C:/Users/hah50/Downloads/ece-350-tank-shooter/project_1/project_1.runs/synth_1/.Xil/Vivado-4804-P1-04/realtime/clk_wiz_0_stub.v
      C:/Users/hah50/Downloads/ece-350-tank-shooter/BulletRAM.v
      C:/Users/hah50/Downloads/ece-350-tank-shooter/CPU/MMIO.v
      C:/Users/hah50/Downloads/ece-350-tank-shooter/CPU/RAM.v
      C:/Users/hah50/Downloads/ece-350-tank-shooter/CPU/ROM.v
      C:/Users/hah50/Downloads/ece-350-tank-shooter/CPU/add.v
      C:/Users/hah50/Downloads/ece-350-tank-shooter/CPU/alu.v
      C:/Users/hah50/Downloads/ece-350-tank-shooter/CPU/bitwise_and.v
      C:/Users/hah50/Downloads/ece-350-tank-shooter/CPU/bitwise_not.v
      C:/Users/hah50/Downloads/ece-350-tank-shooter/CPU/bitwise_or.v
      C:/Users/hah50/Downloads/ece-350-tank-shooter/CPU/cla_block.v
      C:/Users/hah50/Downloads/ece-350-tank-shooter/CPU/counter.v
      C:/Users/hah50/Downloads/ece-350-tank-shooter/CPU/dffe_ref.v
      C:/Users/hah50/Downloads/ece-350-tank-shooter/CPU/dffe_ref_negedge.v
      C:/Users/hah50/Downloads/ece-350-tank-shooter/CPU/divider.v
      C:/Users/hah50/Downloads/ece-350-tank-shooter/CPU/inverter.v
      C:/Users/hah50/Downloads/ece-350-tank-shooter/CPU/multdiv.v
      C:/Users/hah50/Downloads/ece-350-tank-shooter/CPU/multiplier.v
      C:/Users/hah50/Downloads/ece-350-tank-shooter/CPU/mux_2_33bit.v
      C:/Users/hah50/Downloads/ece-350-tank-shooter/CPU/mux_2_to_1.v
      C:/Users/hah50/Downloads/ece-350-tank-shooter/CPU/mux_2_to_1_single.v
      C:/Users/hah50/Downloads/ece-350-tank-shooter/CPU/mux_4_33bit.v
      C:/Users/hah50/Downloads/ece-350-tank-shooter/CPU/mux_4_to_1.v
      C:/Users/hah50/Downloads/ece-350-tank-shooter/CPU/mux_4_to_1_single.v
      C:/Users/hah50/Downloads/ece-350-tank-shooter/CPU/mux_8_33bit.v
      C:/Users/hah50/Downloads/ece-350-tank-shooter/CPU/mux_8_to_1.v
      C:/Users/hah50/Downloads/ece-350-tank-shooter/CPU/processor.v
      C:/Users/hah50/Downloads/ece-350-tank-shooter/CPU/regfile.v
      C:/Users/hah50/Downloads/ece-350-tank-shooter/CPU/register.v
      C:/Users/hah50/Downloads/ece-350-tank-shooter/CPU/register_128_f.v
      C:/Users/hah50/Downloads/ece-350-tank-shooter/CPU/register_1bit.v
      C:/Users/hah50/Downloads/ece-350-tank-shooter/CPU/register_1bit_f.v
      C:/Users/hah50/Downloads/ece-350-tank-shooter/CPU/register_32.v
      C:/Users/hah50/Downloads/ece-350-tank-shooter/CPU/register_64.v
      C:/Users/hah50/Downloads/ece-350-tank-shooter/CPU/register_64_f.v
      C:/Users/hah50/Downloads/ece-350-tank-shooter/CPU/register_66.v
      C:/Users/hah50/Downloads/ece-350-tank-shooter/CPU/register_96_f.v
      C:/Users/hah50/Downloads/ece-350-tank-shooter/CPU/sll.v
      C:/Users/hah50/Downloads/ece-350-tank-shooter/CPU/sra.v
      C:/Users/hah50/Downloads/ece-350-tank-shooter/CPU/sub.v
      C:/Users/hah50/Downloads/ece-350-tank-shooter/CPU/t_flip_flop.v
      C:/Users/hah50/Downloads/ece-350-tank-shooter/CPU/Wrapper.v
    }
      rt::read_vhdl -lib xpm C:/Xilinx/Vivado/2021.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList C:/Users/hah50/Downloads/ece-350-tank-shooter/project_1/project_1.runs/synth_1/.Xil/Vivado-4804-P1-04/realtime/Wrapper_synth.xdc
    rt::sdcChecksum
    set rt::top Wrapper
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {C:/Users/hah50/Downloads/ece-350-tank-shooter/project_1/project_1.cache/wt}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "C:/Users/hah50/Downloads/ece-350-tank-shooter/project_1/project_1.runs/synth_1/.Xil/Vivado-4804-P1-04/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
